### ISSUE TITLE
Re-installing tendrl on the same node fails

### ISSUE THREAD

**Issue by cybernth** [Tendrl/tendrl-ansible#83] opened 2018-03-06 02:54 UTC
tendrl-api fails to get enabled and started. Please have a look at this console output:

TASK [tendrl-ansible.tendrl-server : Store tendrl admin password to local /root/password file] ********************************************************************************************************************
ok: [server]

TASK [tendrl-ansible.tendrl-server : Enable tendrl-api service] ***************************************************************************************************************************************************
fatal: [server]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service tendrl-api: host"}

RUNNING HANDLER [tendrl-ansible.tendrl-server : restart tendrl-api] ***********************************************************************************************************************************************

RUNNING HANDLER [tendrl-ansible.tendrl-server : restart rsyslog] **************************************************************************************************************************************************

RUNNING HANDLER [tendrl-ansible.tendrl-server : restart tendrl-node-agent] ****************************************************************************************************************************************
	to retry, use: --limit @/root/site.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
server                     : ok=34   changed=9    unreachable=0    failed=1

**Comment by dahorak** [comment] 2018-03-06 07:22
I think, that this is issue in *tendrl-api* (installation/uninstallation process). It might be workarounded in *tendrl-ansible*, but it will be definitely better to fix the root cause in the *tendrl-api* package.

**Comment by cybernth** [comment] 2018-03-06 08:25
@dahorak , Could you please add some details about that or raise specific issue on the api repo?
I agree, if its something related to installation/un-installation, better to fix there.

**Comment by dahorak** [comment] 2018-03-06 08:28
I'll try to debug it and file issue with relevant data.

**Comment by dahorak** [comment] 2018-03-06 09:08
I've created related issue for tendrl-api: https://github.com/Tendrl/api/issues/378

**Comment by mbukatov** [comment] 2018-03-06 09:49
@dahorak thanks for looking into this

**Comment by dahorak** [comment] 2018-03-07 09:10
I've reproduced the issue on *release* packages (`tendrl-api-1.6.0-1.el7.centos.noarch`) and verified that it is fixed by https://github.com/Tendrl/api/pull/379 in latest packages from master branch (`tendrl-api-1.6.0-20180306T115141.3b74256.noarch`), so I thing we can close this ticket.

**Comment by mbukatov** [comment] 2018-03-07 09:13
@dahorak thank you for verification, closing

**Closed as completed by mbukatov** 2018-03-07 09:13 UTC
