### ISSUE TITLE
provisioner/gluster tag missing on tendrl node

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/tendrl-ansible#14] opened 2017-06-21 20:56 UTC
when i tried to install today the provisioner/gluster tag was missing on the tendrl node - it is required there right?

**Comment by mbukatov** [comment] 2017-06-22 06:14
As far as I know, Tendrl mandates that `provisioner/gluster` should be added into `/etc/tendrl/node-agent/node-agent.conf.yaml` file on a single machine of Tendrl Storage Node role. Which is what the playbook does right now.

Do you see that the tag has been configured on a single storage node while not on the others?

On the other hand, current https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference  states that the tag should be added on every storage node:

> ## Configure Node Agent
>
> Edit the below configurations for connecting to the etcd server
> 
> Open /etc/tendrl/node-agent/node-agent.conf.yaml
> 
> Update → 
>
> etcd_connection = <IP of etcd server>
> 
> Add a new tag under tags(Only for Gluster Nodes):
>
> provisioner/gluster

which is what tendrl-ansible did until I fixed it in commit 73e740f78a09d56469dbd1b63a4509fa03f54eca based on @dahorak 's feedback.

I can't find this being discussed in tendrl-devel list, which means that I have missed this after the fix, sorry for that. On the other hand, missed details like this one is the reason why the [only way how to ensure that docs and tendrl-ansible matches is final review](https://github.com/Tendrl/tendrl-ansible/issues/9) after already raised questions are incorporated in the docs.

**Comment by mbukatov** [comment] 2017-06-22 15:35
Status update: the question from https://github.com/Tendrl/tendrl-ansible/issues/14#issuecomment-310285834 has been resolved by [wiki commit 00a3649](https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference/_compare/0f43d3700bdad962d1fdeb4757810d16c307ef60...00a364919488b2fafb729716dab144429f5d3059). Thanks @shtripat for the quick update!

This means that the expected behavior is to have `provisioner/gluster` enabled on a single storage machine only. @japplewhite is that what you see in your case or do you miss the tag completely, having no machine with the tag at all?

**Comment by mbukatov** [comment] 2017-06-23 14:09
Btw it turns out that [we were actually missing the tag, but in qe environment based on usmqe-setup](https://github.com/Tendrl/usmqe-setup/pull/114) - usmqe-setup is now fixed and tendrl-ansible itself was not affected.

**Comment by mbukatov** [comment] 2017-08-22 15:56
Status Update for Tendrl 1.5.0: [Tendrl Package Installation Reference](https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference) mentions:

> Add a new tag under tags (This is applicable only to gluster and is required to be set only on one of the nodes):
>
> provisioner/gluster

And role tendrl-storage-node contains task to set the tag:

```
- name: Add provisioner/gluster tag into node-agent.conf.yaml
  lineinfile:
    dest: /etc/tendrl/node-agent/node-agent.conf.yaml
    insertafter: '^tags:$'
    line: "  - provisioner/gluster"
  notify:
    - restart tendrl-node-agent
  when: tendrl_gluster_provisioning_support == True
  run_once: true
```

So there is no bug in tendrl-ansible I'm aware of.

**Comment by mbukatov** [comment] 2017-08-28 06:52
Since Tendrl 1.5.1, the tag shouldn't be configured by tendrl-ansible, see also: https://github.com/Tendrl/tendrl-ansible/issues/27

**Comment by mbukatov** [comment] 2017-08-28 06:53
Closing for the following reasons:

1) There is no bug in tendrl ansible reated to the tags I'm aware of (https://github.com/Tendrl/tendrl-ansible/issues/14#issuecomment-324071267)
2) Configuration of tag is no longer part of the installation since Tendrl 1.5.1 (https://github.com/Tendrl/tendrl-ansible/issues/14#issuecomment-325274256)

**Closed as completed by mbukatov** 2017-08-28 06:53 UTC
Labels: invalid
