### ISSUE TITLE
Tendrl-API fails to be set up properly

### ISSUE THREAD

**Issue by mulbc** [Tendrl/tendrl-ansible#1] opened 2017-01-25 19:58 UTC
After running the Ansible scripts, `tendrl-api` is not set up properly and returns:
```
# curl localhost:9292/1.0/ping
<h1>Internal Server Error</h1>
```

inside of the console I can see a stack trace from Puma:
```
Etcd::KeyNotFound - Key not found:
	/usr/share/gems/gems/etcd-0.3.0/lib/etcd/client.rb:141:in `process_http_request'
	/usr/share/gems/gems/etcd-0.3.0/lib/etcd/client.rb:114:in `api_execute'
	/usr/share/gems/gems/etcd-0.3.0/lib/etcd/keys.rb:22:in `get'
	/usr/share/tendrl-api/node.rb:6:in `block in <class:Node>'   <--- Watch this
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `[]'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:957:in `block in filter!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:957:in `each'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:957:in `filter!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1075:in `block in dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/share/gems/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `call'
	/usr/share/gems/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

Looking at https://github.com/Tendrl/api/blob/master/node.rb#L6 it appears like there is a call to get a key, which is not yet present in the etcd.
Not even the rake seed task is creating this key:
https://github.com/Tendrl/api/blob/master/Rakefile#L12

**Comment by brainfunked** [comment] 2017-01-26 11:24
That particular key is added by the node agent. It is required for the API to function at all. As I have commented on the issue on https://github.com/Tendrl/api/issues/61, even if this exception is caught, the server response would still be a 5xx.

The problem is that the node agent is responsible for pushing those configuration keys, which drive the entire tendrl deployment, API included. The proper way to setup the deployment is to start a node agent and then start the API. On startup, the node agent will push the appropriate keys to etcd.

Given that the canonical data resides with the node agent, it would not be possible to seed it via rake either. The most that could be done would be to ensure that the directory is created. But the most that does is to avoid the exception.

Also, FYI, as of node agent [v1.2](https://github.com/Tendrl/node-agent/tree/v1.2), the location of the keys have changed.

**Comment by japplewhite** [comment] 2017-01-26 16:56
@brainfunked we can't have a situation where the console is expecting a node agent before it functions properly. that is a reverse dependency in the install use case where all that exists is Tendrl itself. We have to have a workaround for this in some way. Can we simply pre-create a dummy key to allow the api to start and then update it?

**Comment by brainfunked** [comment] 2017-01-27 05:07
@japplewhite etcd, node agent and the API together form the core stack. At least one node agent instance will be mandatory for any functionality. API is just an interface to etcd. Node agents do all the work. However, with the changes introduced in https://github.com/Tendrl/specifications/issues/44, the first node agent can be run anywhere, including on the etcd and API nodes.

Regarding this specific issue, there has been some discussion between Rohan and I about a better way to handle the initial push and the subsequent updates of the definition files, without relying on the node agent. We don't have a fully formed solution yet. We may have one come Tendrl 3.

**Comment by mulbc** [comment] 2017-01-27 17:19
If it is not possible to pre-seed etcd - why can't we then at least avoid crashing on the API side?
I'm sure the API would be able to serve a friendly "No data yet" if the etcd does not include the data we need to work yet.

Crashing should only happen in an error case - "You have not finished building up all components" is not really an error case.

**Comment by japplewhite** [comment] 2017-03-22 20:01
It looks like the API now requires something like this:

[root@tendrl } # cd /usr/share/tendrl-api
[root@tendrl tendrl-api]# RACK_ENV=production rake etcd:load_admin
"Generating default Tendrl admin"
"Generated default admin"
"Username: admin"
"Password: 12dc2955"

I assume this means that the docs need updating at: 
https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference
@anivargi  ?

**Comment by mbukatov** [comment] 2017-06-13 15:43
After installing *Tendrl Server* using new ansible code, `tendrl-api` service works:

```
$ curl http://mbukatov-usm1-server.usmqe.example.com/api/1.0/ping; echo
{"status":"Ok"}
$
```

So I'm closing this.

That said, is there any valid scenario related to this problem which is still valid and requires attention of  @Tendrl/qe to recheck it with current release? @zeichenanonym @japplewhite @brainfunked ?

**Closed as completed by mbukatov** 2017-06-13 15:43 UTC
